// Loader
export const START_LOADER = "START_LOADER";
export const END_LOADER = "END_LOADER";

// Auth
export const REMIND_ME = "REMIND_ME";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTHLOGOUTT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_SUCCESS = "RESET_SUCCESS";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const LOADING_PROFILE = "LOADING_PROFILE";
export const ERROR_PROFILE = "ERROR_PROFILE";

// Company
export const GET_COMPANY = "GET_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const CLEAR_COMPANY = "CLEAR_COMPANY";
export const LOADING_COMPANY = "LOADING_COMPANY";
export const ERROR_COMPANY = "ERROR_COMPANY";

// Account
export const GET_ACCOUNT = "GET_ACCOUNT";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";
export const LOADING_ACCOUNT = "LOADING_ACCOUNT";
export const ERROR_ACCOUNT = "ERROR_ACCOUNT";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
export const CLEAR_CURRENT_ACCOUNT = "CLEAR_CURRENT_ACCOUNT";

// Transaction
export const GET_TRANSACTION = "GET_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const CLEAR_TRANSACTION = "CLEAR_TRANSACTION";
export const LOADING_TRANSACTION = "LOADING_TRANSACTION";
export const ERROR_TRANSACTION = "ERROR_TRANSACTION";

// Action
export const GET_ACTION = "GET_ACTION";
export const CREATE_ACTION = "CREATE_ACTION";
export const DELETE_ACTION = "DELETE_ACTION";
export const CLEAR_ACTION = "CLEAR_ACTION";
export const LOADING_ACTION = "LOADING_ACTION";
export const ERROR_ACTION = "ERROR_ACTION";

// Transfer
export const GET_TRANSFER = "GET_TRANSFER";
export const CREATE_TRANSFER = "CREATE_TRANSFER";
export const DELETE_TRANSFER = "DELETE_TRANSFER";
export const CLEAR_TRANSFER = "CLEAR_TRANSFER";
export const LOADING_TRANSFER = "LOADING_TRANSFER";
export const ERROR_TRANSFER = "ERROR_TRANSFER";

// Category
export const GET_CATEGORY = "GET_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const LOADING_CATEGORY = "LOADING_CATEGORY";
export const ERROR_CATEGORY = "ERROR_CATEGORY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const CLEAR_CURRENT_CATEGORY = "CLEAR_CURRENT_CATEGORY";

// Tag
export const GET_TAG = "GET_TAG";
export const CREATE_TAG = "CREATE_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const CLEAR_TAG = "CLEAR_TAG";
export const LOADING_TAG = "LOADING_TAG";
export const ERROR_TAG = "ERROR_TAG";

// Calendar
export const SET_CALENDAR = "SET_CALENDAR";
export const CLEAR_CALENDAR = "CLEAR_CALENDAR";
